# Generated by Django 4.2.11 on 2024-04-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('raison_sociale', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('rue', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('zipcode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('npa', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('localite', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('sexe_interlocuteur', models.CharField(blank=True, choices=[('M', 'M'), ('Mme', 'Mme')], default='', max_length=20, null=True)),
                ('nom_interlocuteur', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prenom_interlocuteur', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('duree_contrat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mobile', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mensualite', models.FloatField(default=0)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contrat')),
            ],
        ),
    ]
