# Generated by Django 4.2.11 on 2024-04-11 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contrat_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_contrat',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
