# Generated by Django 4.2.11 on 2024-04-13 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contrat_sexe_interlocuteur_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='paye_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='statut',
            field=models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Payé', 'Payé'), ('Achevé', 'Achevé')], default='En cours', max_length=200, null=True),
        ),
    ]
