# Generated by Django 4.2.11 on 2024-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cycle_created_at_cycle_paye_le_cycle_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='duree_prolongation',
            field=models.IntegerField(default=0),
        ),
    ]
