# Generated by Django 4.2.11 on 2024-04-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cycle_duree_prolongation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='duree_prolongation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
