# Generated by Django 4.2.11 on 2024-04-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cycle_duree_prolongation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='affectation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
