# Generated by Django 4.2.11 on 2024-04-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_contrat_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Utilisateur', 'Utilisateur')], default='Administrateur', max_length=100),
        ),
    ]
